### PR TITLE
Fix bad reference unassigned variable

### LINKED ISSUE #10: Error when using "plantuml.jar"
Hello and thanks for a nice plugin. Have an issue when using "plantuml.jar".

From the code:

    try:
        output = None
        if use_web:
            output = plantuml_web(uml_path)
        else:
            plantuml_path = os.path.abspath(args.plantuml_path or PLANTUMLPATH)
            plantuml_exec(uml_path, plantuml_path=plantuml_path)
        svg_name = output[0]
        return SVG(filename=svg_name)
    finally:

When "use_web" is "false" the output variable will be "None" meaning that there will be an exception on line: 

    svg_name = output[0]

Suggests that the line above is changed to:

            output = plantuml_exec(uml_path, plantuml_path=plantuml_path)

### PR DESCRIPTION
**Pull request by jacobdr**
Fixes #10

### CODE REVIEW

**Comment by jbn** [comment]
Thanks, @jacobdr!

I'll bump the version shortly!

**Comment by jacobdr** [comment]
Cheers. Easiest fix of all time! Clearly just a small mistake from the refactor left on a very uncommon codepath...

Jacob

**Comment by jbn** [comment]
Except, not actually an uncommon codepath for me! I use the local JAR in my dissertation code because it's a lot of requests. I just haven't built it in a while. So, thanks again, from me in a future that no longer exists!

**Comment by jbn** [comment]
(P.S. Pushed to PyPi.)

**Pull request merged**
